### ISSUE TITLE
QuartzNetScheduler 0.3.2.0 missing SetSchedulerListeners method

### ISSUE THREAD

**Issue by doctorhilarius** [castleproject-deprecated/QuartzNetIntegration#16]
I just upgraded to 0.3.2.0 b/c I upgraded Quartz, but I'm finding that the new implementation of IScheduler, QuartzNetScheduler, no longer includes the SetSchedulerListeners method, so my custom implementation of ISchedulerListener is not getting added to the SchedulerListeners. Is this just an oversight or is it intentional for some reason? Is there a plan to add it back?

**Comment by mausch** [comment]
I think we should upgrade this project to the latest version of Quartz first (2.3.3 as of this writing), deal with any breaking changes and then push a new release.
Do you want to give that a try and send me a pull request? Let me know if you find any breaking changes you can't fix.

**Comment by jonorossi** [comment]
This issue is stale, closing. @kristofdc just updated this project to Quartz v3.0.2.
